name: build-test-deploy
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: setup Go
              uses: actions/setup-go@v2
              with:
                  go-version: '1.18.0'

            - name: build
              run: go build -v .

            - name: test
              run: go test -v control input translator it

            - name: unit test coverage
              run: go test -cover control input translator

            - name: integration test coverage
              run: go test it -coverpkg=control,input,translator

    deploy:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - uses: actions/checkout@v2
            - name: login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - name: deploy to Docker registry
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: quincinia/go-tr:latest
