name: build-test-deploy
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: setup Go
              uses: actions/setup-go@v2
              with:
                  go-version: '1.18.0'

            - name: build
              run: go build -v .

            - name: test
              run: go test -v control input translator it

    deploy:
        runs-on: ubuntu-latest
        needs: [build]
        steps:
            - uses: actions/checkout@v2
            - name: deploy to Docker registry
              uses: docker/build-push-action@v1
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
                repository: quincinia/go-tr
                tag_with_ref: true
